import { Service, GraphNode, GraphEdge, Interrupt, ActivityEvent, Field } from './types'

export const services: Service[] = [
  {
    id: 'vets-service',
    name: 'vets-service',
    status: 'breaking',
    language: 'Java',
    description: 'Veterinarian data provider — source of breaking change in PR #42',
  },
  {
    id: 'api-gateway',
    name: 'api-gateway',
    status: 'interrupt',
    language: 'Java',
    description: 'API gateway routing all consumer requests — interrupt pending on consultationFee units',
  },
  {
    id: 'react-frontend',
    name: 'react-frontend',
    status: 'healed',
    language: 'TypeScript',
    description: 'React frontend — auto-healed (ownerPhone null-safe fix applied via PR #18)',
  },
  {
    id: 'customers-service',
    name: 'customers-service',
    status: 'healthy',
    language: 'Java',
    description: 'Customer and owner data management',
  },
  {
    id: 'visits-service',
    name: 'visits-service',
    status: 'healthy',
    language: 'Java',
    description: 'Appointment and visit scheduling',
  },
  {
    id: 'discovery-server',
    name: 'discovery-server',
    status: 'healthy',
    language: 'Java',
    description: 'Eureka service registry — all services registered here',
  },
]

export const graphNodes: GraphNode[] = [
  {
    id: 'discovery-server',
    serviceId: 'discovery-server',
    label: 'discovery-server',
    status: 'healthy',
    position: { x: 50, y: 200 },
  },
  {
    id: 'customers-service',
    serviceId: 'customers-service',
    label: 'customers-service',
    status: 'healthy',
    position: { x: 280, y: 60 },
  },
  {
    id: 'visits-service',
    serviceId: 'visits-service',
    label: 'visits-service',
    status: 'healthy',
    position: { x: 280, y: 340 },
  },
  {
    id: 'vets-service',
    serviceId: 'vets-service',
    label: 'vets-service',
    status: 'breaking',
    position: { x: 520, y: 200 },
  },
  {
    id: 'api-gateway',
    serviceId: 'api-gateway',
    label: 'api-gateway',
    status: 'interrupt',
    position: { x: 760, y: 200 },
    hasInterrupt: true,
  },
  {
    id: 'react-frontend',
    serviceId: 'react-frontend',
    label: 'react-frontend',
    status: 'healed',
    position: { x: 1000, y: 200 },
  },
]

export const graphEdges: GraphEdge[] = [
  {
    id: 'vets-api',
    source: 'vets-service',
    target: 'api-gateway',
    edgeType: 'breaking',
    label: 'consultationFee broken',
  },
  {
    id: 'vets-frontend',
    source: 'vets-service',
    target: 'react-frontend',
    edgeType: 'healed',
    label: 'ownerPhone healed',
  },
  {
    id: 'customers-api',
    source: 'customers-service',
    target: 'api-gateway',
    edgeType: 'healthy',
  },
  {
    id: 'visits-api',
    source: 'visits-service',
    target: 'api-gateway',
    edgeType: 'healthy',
  },
  {
    id: 'api-frontend',
    source: 'api-gateway',
    target: 'react-frontend',
    edgeType: 'healthy',
  },
  {
    id: 'discovery-vets',
    source: 'discovery-server',
    target: 'vets-service',
    edgeType: 'registry',
  },
  {
    id: 'discovery-api',
    source: 'discovery-server',
    target: 'api-gateway',
    edgeType: 'registry',
  },
]

export const interrupts: Interrupt[] = [
  {
    id: 'interrupt-1',
    service: 'api-gateway',
    field: 'consultationFee',
    question: 'How should api-gateway handle existing consultationFee values?',
    context:
      'consultationFee changed from cents (int) to dollars (decimal) in vets-service PR #42. VetController.java:203 passes this value directly to the billing calculation. Existing stored values are in cents — downstream billing logic assumes integer cents.',
    options: [
      {
        id: 'divide',
        label: 'Divide by 100 at read time',
        description: 'Keep billing logic unchanged. Convert: fee / 100.0 when reading from vets-service.',
      },
      {
        id: 'update-billing',
        label: 'Update billing to work with dollars directly',
        description:
          'Cleaner long-term. Ripple updates billing calculation and all display formatting to expect decimal dollars.',
      },
      {
        id: 'manual',
        label: "I'll handle this manually",
        description: 'Dismiss. Ripple skips api-gateway and flags decision in audit log.',
      },
    ],
    sourcePR: 'vets-service',
    sourcePRNumber: 42,
    createdAt: '2024-01-15T10:30:00Z',
    timeAgo: '2 hours ago',
  },
]

export const activityEvents: ActivityEvent[] = [
  {
    id: 'evt-1',
    type: 'analyzed',
    title: 'PR #42 analyzed in vets-service',
    service: 'vets-service',
    prNumber: 42,
    timeAgo: '2 hours ago',
    timestamp: '2024-01-15T10:28:00Z',
  },
  {
    id: 'evt-2',
    type: 'interrupt_created',
    title: 'Interrupt created for api-gateway',
    service: 'api-gateway',
    field: 'consultationFee',
    prNumber: 42,
    timeAgo: '2 hours ago',
    timestamp: '2024-01-15T10:30:00Z',
  },
  {
    id: 'evt-3',
    type: 'auto_healed',
    title: 'react-frontend auto-healed',
    service: 'react-frontend',
    field: 'ownerPhone',
    prNumber: 18,
    timeAgo: '2 hours ago',
    timestamp: '2024-01-15T10:31:00Z',
  },
  {
    id: 'evt-4',
    type: 'fix_pr_raised',
    title: 'Fix PR #18 raised for react-frontend',
    service: 'react-frontend',
    prNumber: 18,
    timeAgo: '2 hours ago',
    timestamp: '2024-01-15T10:32:00Z',
  },
  {
    id: 'evt-5',
    type: 'analyzed',
    title: 'PR #37 analyzed in customers-service',
    service: 'customers-service',
    prNumber: 37,
    timeAgo: '1 day ago',
    timestamp: '2024-01-14T14:15:00Z',
  },
  {
    id: 'evt-6',
    type: 'auto_healed',
    title: 'visits-service auto-healed after customers-service PR #37',
    service: 'visits-service',
    field: 'ownerId',
    prNumber: 22,
    timeAgo: '1 day ago',
    timestamp: '2024-01-14T14:18:00Z',
  },
  {
    id: 'evt-7',
    type: 'fix_pr_raised',
    title: 'Fix PR #22 raised for visits-service',
    service: 'visits-service',
    prNumber: 22,
    timeAgo: '1 day ago',
    timestamp: '2024-01-14T14:19:00Z',
  },
  {
    id: 'evt-8',
    type: 'indexed',
    title: 'vets-service re-indexed after PR #38 merge',
    service: 'vets-service',
    prNumber: 38,
    timeAgo: '2 days ago',
    timestamp: '2024-01-13T09:45:00Z',
  },
  {
    id: 'evt-9',
    type: 'indexed',
    title: 'discovery-server indexed — 6 services registered',
    service: 'discovery-server',
    timeAgo: '3 days ago',
    timestamp: '2024-01-12T11:00:00Z',
  },
  {
    id: 'evt-10',
    type: 'analyzed',
    title: 'PR #31 analyzed in visits-service',
    service: 'visits-service',
    prNumber: 31,
    timeAgo: '4 days ago',
    timestamp: '2024-01-11T16:30:00Z',
  },
]

export const fields: Field[] = [
  {
    id: 'f1',
    name: 'consultationFee',
    type: 'decimal',
    service: 'vets-service',
    consumers: 2,
    status: 'breaking',
    lastChanged: '2 hours ago',
  },
  {
    id: 'f2',
    name: 'ownerPhone',
    type: 'string (removed)',
    service: 'vets-service',
    consumers: 1,
    status: 'breaking',
    lastChanged: '2 hours ago',
  },
  {
    id: 'f3',
    name: 'petAge',
    type: 'string',
    service: 'vets-service',
    consumers: 3,
    status: 'changed',
    lastChanged: '2 hours ago',
  },
  {
    id: 'f4',
    name: 'ownerContact.phone',
    type: 'string',
    service: 'vets-service',
    consumers: 1,
    status: 'changed',
    lastChanged: '2 hours ago',
  },
  {
    id: 'f5',
    name: 'ownerId',
    type: 'long',
    service: 'customers-service',
    consumers: 3,
    status: 'stable',
    lastChanged: '1 day ago',
  },
  {
    id: 'f6',
    name: 'ownerFirstName',
    type: 'string',
    service: 'customers-service',
    consumers: 2,
    status: 'stable',
    lastChanged: '5 days ago',
  },
  {
    id: 'f7',
    name: 'ownerLastName',
    type: 'string',
    service: 'customers-service',
    consumers: 2,
    status: 'stable',
    lastChanged: '5 days ago',
  },
  {
    id: 'f8',
    name: 'visitDate',
    type: 'LocalDate',
    service: 'visits-service',
    consumers: 2,
    status: 'stable',
    lastChanged: '3 days ago',
  },
  {
    id: 'f9',
    name: 'visitDescription',
    type: 'string',
    service: 'visits-service',
    consumers: 1,
    status: 'stable',
    lastChanged: '3 days ago',
  },
  {
    id: 'f10',
    name: 'petId',
    type: 'int',
    service: 'visits-service',
    consumers: 3,
    status: 'stable',
    lastChanged: '4 days ago',
  },
]

export const ecosystemStats = {
  totalServices: 6,
  pendingInterrupts: 1,
  autoHealed: 4,
  fieldsIndexed: 47,
}

export const prChanges = [
  {
    field: 'ownerPhone',
    change: 'REMOVED (replaced by ownerContact.phone)',
    type: 'breaking' as const,
  },
  {
    field: 'petAge',
    change: 'int → string (format: "2 years")',
    type: 'changed' as const,
  },
  {
    field: 'consultationFee',
    change: 'int cents → decimal dollars',
    type: 'interrupt' as const,
  },
]
