from __future__ import annotations

from typing import Optional, Protocol

from ripple.rib.graph.schema import (
    BlastRadius,
    ConsumerBelief,
    Disagreement,
    FieldNode,
    FieldUsage,
    HistorySignal,
    IngestionResult,
    SemanticProfile,
    SymbolNode,
)


class RippleStore(Protocol):
    def upsert_field(self, field: FieldNode) -> None: ...

    def upsert_symbol(self, symbol: SymbolNode) -> None: ...

    def upsert_usage(self, usage: FieldUsage) -> None: ...

    def upsert_history_signal(self, signal: HistorySignal) -> None: ...

    def upsert_semantic_profile(self, profile: SemanticProfile) -> None: ...

    def upsert_consumer_belief(self, belief: ConsumerBelief) -> None: ...

    def upsert_disagreement(self, disagreement: Disagreement) -> None: ...

    def get_field(self, field_fqn: str) -> Optional[FieldNode]: ...

    def get_semantic_profile(self, field_fqn: str) -> Optional[SemanticProfile]: ...

    def get_consumer_belief(
        self, consumer_service: str, field_fqn: str
    ) -> Optional[ConsumerBelief]: ...

    def get_usages_for_field(self, field_fqn: str) -> list[FieldUsage]: ...

    def get_history_signals(self, field_fqn: str) -> list[HistorySignal]: ...

    def get_active_disagreements(self) -> list[Disagreement]: ...

    def get_disagreements_for_field(self, field_fqn: str) -> list[Disagreement]: ...

    def get_blast_radius(self, field_fqn: str) -> BlastRadius: ...

    def get_all_fields(self) -> list[FieldNode]: ...

    def get_fields_for_service(self, service_name: str) -> list[FieldNode]: ...

    def mark_disagreement_resolved(self, field_fqn: str, consumer_service: str, fix_pr_url: str) -> None: ...

    def get_file_content_hash(self, file_path: str, service_name: str) -> Optional[str]: ...

    def upsert_indexed_file(self, service_name: str, file_path: str, content_hash: str) -> None: ...
